# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

env:
  NuGetDirectory: ${{ github.workspace }}/nuget
  ArtifactName: nuget-artifact

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.ArtifactName }}
          path: ${{ env.NuGetDirectory }}/*.nupkg # A file, directory or wildcard pattern that describes what to upload
          if-no-files-found: error
          retention-days: 7
  
  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download NuGet artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{ env.ArtifactName }}
          path: ${{ env.NuGetDirectory }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Add NuGet source
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --name github "https://nuget.pkg.github.com/ArtemStepanov/index.json"
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github" --skip-duplicate
          }
